FlameAndWax.Customer/Controllers/CartController.cs
using FlameAndWax.Customer.Models;
using FlameAndWax.Data.Constants;
using FlameAndWax.Data.Models;
using FlameAndWax.Services.Helpers;
using FlameAndWax.Services.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FlameAndWax.Customer.Controllers
{
    [Authorize(Roles = nameof(Constants.Roles.Customer))]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IUserProfileService _userProfileService;
        private readonly IConfiguration _configuration;

        private string ConnectionString { get; }

        public CartController(ICartService cartService, IConfiguration configuration, IUserProfileService userProfileService)
        {
            _cartService = cartService;
            _configuration = configuration;
            _userProfileService = userProfileService;
            ConnectionString = _configuration.GetConnectionString("FlameAndWaxDBConnection");
        }

        public IActionResult Index()
        {
            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            return View(Cart.GetCartItems(userLoggedIn));
        }

        public IActionResult IncrementProductCount(int productId)
        {
            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            var result = Cart.IncrementProductCount(productId, userLoggedIn);

            if (!result) return BadRequest("Not Enough Products!");
            return PartialView("CartTablePartial", new CartViewModel { CartProducts = Cart.GetCartItems(userLoggedIn) });
        }

        public IActionResult DecrementProductCount(int productId)
        {
            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            Cart.DecrementProductCount(productId, userLoggedIn);
            return PartialView("CartTablePartial", new CartViewModel { CartProducts = Cart.GetCartItems(userLoggedIn) });
        }

        public IActionResult DeleteCartItem(int productId)
        {
            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            Cart.RemoveCartItem(productId, userLoggedIn);
            return PartialView("CartTablePartial", new CartViewModel { CartProducts = Cart.GetCartItems(userLoggedIn) });
        }

        public IActionResult RefreshCart()
        {
            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            return PartialView("CartTablePartial", new CartViewModel { CartProducts = Cart.GetCartItems(userLoggedIn) });
        }

        public async Task<IActionResult> Checkout()
        {
            var cart = JsonConvert.DeserializeObject<CartViewModel>(TempData["CartViewModel"].ToString());

            if (cart.CartProducts == null) 
                return BadRequest("Cart Products is null");

            var userLoggedInID = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.NameIdentifier).Value;
            var userLoggedInUsername = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;

            var taskOrderDetails = BuildOrderDetails(cart.CartProducts, userLoggedInUsername);
            var resultOrderDetails = await Task.WhenAll(taskOrderDetails);
            var totalOrderCost = resultOrderDetails.Select(x => x.TotalPrice).Sum();

            var modeOfPayment = ServiceHelper.BuildModeOfPayment(cart.ModeOfPayment.ToString());
            var courierType = ServiceHelper.BuildCourier(cart.Courier.ToString());
            var order = new OrderModel
            {
                Customer = new CustomerModel { CustomerId = int.Parse(userLoggedInID) },
                Employee = new EmployeeModel { EmployeeId = -1 },
                DateOrdered = DateTime.UtcNow,
                TotalCost = totalOrderCost,
                ModeOfPayment = modeOfPayment,
                OrderDetails = resultOrderDetails,
                Courier = courierType
            };
            var primaryKeyServiceResult = await _cartService.CheckoutOrderAsync(order, userLoggedInUsername, ConnectionString);

            if (primaryKeyServiceResult.HasError) 
                return BadRequest(primaryKeyServiceResult.ErrorContent);

            Cart.ClearCartItems(userLoggedInUsername);
            return Ok("Successfully Inserted Order!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CartSummary(CartViewModel cart)
        {
            var userLoggedInUsername = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            var userLoggedInID = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.NameIdentifier).Value;
            var totalCost = Cart.GetTotalCartCost(userLoggedInUsername);

            var userProfileServiceResult = await _userProfileService.FetchAccountDetailAsync(int.Parse(userLoggedInID), ConnectionString);
            if (userProfileServiceResult.HasError) return BadRequest(userProfileServiceResult.ErrorContent);

            CartSummaryViewModel cartSummary = new CartSummaryViewModel(totalCost, cart, userProfileServiceResult.Result.Addresses.FirstOrDefault());
            return View(cartSummary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult FinalizeCheckout(CartViewModel cart)
        {
            var userLoggedInUsername = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
            var cartViewModel = new CartViewModel(
                cart.ModeOfPayment,
                cart.Courier,
                Cart.GetCartItems(userLoggedInUsername));

            TempData["CartViewModel"] = JsonConvert.SerializeObject(cartViewModel);
            return RedirectToAction(nameof(Checkout));
        }

        public async Task<IActionResult> AddToCart(int productId, string user)
        {
            var productServiceResult = await _cartService.FetchProductDetailAsync(productId, ConnectionString);
            if (productServiceResult.HasError) return RedirectToAction("Index", "Error", new { productServiceResult.ErrorContent });

            var canStillOrderProduct = true;
            if (productServiceResult.Result.UnitsInStock == 0) canStillOrderProduct = false;
            var productsLeft = productServiceResult.Result.UnitsInStock - productServiceResult.Result.UnitsInOrder;
            if (productsLeft == 0) canStillOrderProduct = false;

            if (!canStillOrderProduct) return BadRequest("Cannot Order! No more products left!");

            var productViewModel = new ProductViewModel(productServiceResult.Result);

            Cart.AddCartItem(productViewModel, user);
            var cartItems = Cart.GetCartItems(user);
            var cartItemCount = cartItems.Count();
            return Ok(cartItemCount);
        }
        private List<Task<OrderDetailModel>> BuildOrderDetails(List<ProductViewModel> cartItems, string userLoggedInUsername)
        {
            var taskOrderDetails = cartItems.Select(async cartItem =>
            {                
                var productPriceServiceResult = await _cartService.FetchProductPriceAsync(cartItem.ProductId, ConnectionString);
                if (productPriceServiceResult.HasError)
                    throw new Exception(productPriceServiceResult.ErrorContent);

                return new OrderDetailModel
                {
                    Product = new ProductModel
                    {
                        ProductId = cartItem.ProductId,
                        ProductPrice = productPriceServiceResult.Result
                    },
                    TotalPrice = productPriceServiceResult.Result * cartItem.QuantityOrdered,
                    Quantity = cartItem.QuantityOrdered,
                };
            }).ToList();
            return taskOrderDetails;
        }
    }
}

FlameAndWax.Customer/Controllers/ContactUsController.cs
using FlameAndWax.Data.Models;
using FlameAndWax.Services.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;

namespace FlameAndWax.Customer.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IContactUsService _contactUsService;
        private readonly IConfiguration _configuration;

        private string ConnectionString { get; }

        public ContactUsController(IContactUsService contactUsService, IConfiguration configuration)
        {
            _contactUsService = contactUsService;
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("FlameAndWaxDBConnection");
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(MessageModel messageModel)
        {
            var customerServiceResult = await _contactUsService.SendMessageAsync(messageModel, ConnectionString);
            if (customerServiceResult.HasError) return BadRequest(new { errorContent = customerServiceResult.ErrorContent});
           
            return Ok();
        }
    }
}

FlameAndWax.Customer/Controllers/OrdersController.cs
using FlameAndWax.Data.Constants;
using FlameAndWax.Data.Models;
using FlameAndWax.Customer.Models;
using FlameAndWax.Services.Helpers;
using FlameAndWax.Services.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FlameAndWax.Customer.Controllers
{
    [Authorize(Roles = nameof(Constants.Roles.Customer))]
    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersService;
        private readonly IConfiguration _configuration;
        private string ConnectionString { get; }

        public OrdersController(IOrdersService ordersService, IConfiguration configuration)
        {
            _ordersService = ordersService;
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("FlameAndWaxDBConnection");
        }

        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 3)
        {
            var customerIdLoggedIn = User.Claims.FirstOrDefault(userId => userId.Type == ClaimTypes.NameIdentifier).Value;
            var ordersServiceResult = await _ordersService.FetchOrdersByStatusAsync(pageNumber, pageSize, int.Parse(customerIdLoggedIn), Constants.OrderStatus.Pending, ConnectionString);
            if (ordersServiceResult.HasError) return BadRequest(new { errorContent = ordersServiceResult.ErrorContent });

            var totalNumberOfOrdersServiceResult = await _ordersService.FetchTotalNumberOfOrdersByOrderStatusAsync(Constants.OrderStatus.Pending, ConnectionString, int.Parse(customerIdLoggedIn));

            var totalNumberOfPages = Math.Ceiling((decimal)totalNumberOfOrdersServiceResult.Result / pageSize);
            ViewData["OrderCount"] = (int)totalNumberOfPages;
            ViewData["OrderStatus"] = nameof(Constants.OrderStatus.Pending);

            var orderViewModels = new List<OrderViewModel>();
            foreach (var order in ordersServiceResult.Result) BuildOrderViewModels(order.OrderDetails, orderViewModels, order);

            return View(orderViewModels);
        }

        public async Task<IActionResult> PageOrders(string orderStatus = nameof(Constants.OrderStatus.Pending), int pageNumber = 1, int pageSize = 3)
        {
            var customerIdLoggedIn = User.Claims.FirstOrDefault(userId => userId.Type == ClaimTypes.NameIdentifier).Value;
            var categorizedOrdersServiceResult = await _ordersService.FetchOrdersByStatusAsync(pageNumber, pageSize, int.Parse(customerIdLoggedIn), ServiceHelper.ConvertStringtoOrderStatus(orderStatus), ConnectionString);
            if (categorizedOrdersServiceResult.HasError) return BadRequest(new { errorContent = categorizedOrdersServiceResult.ErrorContent });

            var totalNumberOfOrdersServiceResult = await _ordersService.FetchTotalNumberOfOrdersByOrderStatusAsync(ServiceHelper.ConvertStringtoOrderStatus(orderStatus), ConnectionString, int.Parse(customerIdLoggedIn));

            var totalNumberOfPages = Math.Ceiling((decimal)totalNumberOfOrdersServiceResult.Result / pageSize);
            ViewData["OrderCount"] = (int)totalNumberOfPages;
            ViewData["OrderStatus"] = orderStatus;

            var orderViewModels = new List<OrderViewModel>();
            foreach (var order in categorizedOrdersServiceResult.Result) BuildOrderViewModels(order.OrderDetails, orderViewModels, order);

            return PartialView("OrdersPartialView", orderViewModels);
        }

        public IActionResult Sort(string status)
        {
            return RedirectToAction(nameof(PageOrders), new { orderStatus = status });
        }

        private void BuildOrderViewModels(
            IEnumerable<OrderDetailModel> orderDetailServiceResult,
            List<OrderViewModel> orderViewModels,
            OrderModel order)
        {            
            var orderDetails = orderDetailServiceResult.Select(orderDetail => new OrderDetailViewModel(orderDetail)).ToList();
            orderViewModels.Add(new OrderViewModel(order, orderDetails));          
        }
    }
}

FlameAndWax.Customer/Controllers/RegisterController.cs
using FlameAndWax.Data.Models;
using FlameAndWax.Customer.Models;
using FlameAndWax.Services.Services.BaseInterface.Interface;
using FlameAndWax.Services.Services.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.IO;
using System.Threading.Tasks;
using static FlameAndWax.Data.Constants.Constants;
using FlameAndWax.Services.Helpers;

namespace FlameAndWax.Customer.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IAccountBaseService<CustomerModel> _accountService;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private string ConnectionString { get; }
        public RegisterController(
            IAccountBaseService<CustomerModel> accountService,
            IConfiguration configuration,
            IWebHostEnvironment webHostEnvironment)
        {
            _accountService = accountService;
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
            ConnectionString = _configuration.GetConnectionString("FlameAndWaxDBConnection");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(UserProfileViewModel newUser)
        {
            EmailSender emailSender = new EmailSender(newUser.Email);
            var code = emailSender.RandomString();

            var customerModel = new CustomerModel
            {
                CustomerName = newUser.Fullname,
                ContactNumber = newUser.ContactNumber,
                Email = newUser.Email,
                Addresses = null,
                Username = newUser.Username,
                Password = newUser.Password,
                Status = CustomerAccountStatus.Pending,
                ProfilePictureLink = await BuildProfilePictureLink(newUser.ProfilePictureFile),
                Code = code
            };

            var registerServiceResult = await _accountService.RegisterAsync(customerModel, ConnectionString);
            if (registerServiceResult.HasError) return BadRequest(new { errorContent = registerServiceResult.ErrorContent });

            await Task.Run(() =>
            {
                emailSender.SendCode(code);
            });

            return Ok();
        }

        private async Task<string> BuildProfilePictureLink(IFormFile profilePictureFile)
        {
            if (profilePictureFile != null)
            {
                var fileExtension = Path.GetExtension(profilePictureFile.FileName);
                var guid = Guid.NewGuid();
                if (fileExtension.Equals(".JPG", StringComparison.CurrentCultureIgnoreCase) ||
                    fileExtension.Equals(".PNG", StringComparison.CurrentCultureIgnoreCase) ||
                    fileExtension.Equals(".JPEG", StringComparison.CurrentCultureIgnoreCase))
                {
                    var saveImage = Path.Combine(_webHostEnvironment.WebRootPath, @"images\customers", $"{guid}{profilePictureFile.FileName}");
                    var stream = new FileStream(saveImage, FileMode.Create);
                    await profilePictureFile.CopyToAsync(stream);
                    return @$"images\customers\{guid}{profilePictureFile.FileName}";
                }
            }
            return string.Empty;
        }
    }
}

FlameAndWax.Customer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Flame and Wax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/sweetalert/sweetalert.css" rel="stylesheet" />
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
</head>

<body style="background-color:floralwhite;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom navbar-light box-shadow mb-3 fixed-top"
            style="background-color: #e4e2da" ;>
            <div class="container">
                <a class="navbar-brand" style="color: #a68245; " asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/icons/flameAndWaxLogo.png" width="37" height="30"
                        class="d-inline-block align-top" alt="">
                    Flame And Wax
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products"
                                asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ContactUs" asp-action="Index"
                                >Contact Us</a>
                        </li>                        
                    </ul>

                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            var userLoggedIn = User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value;
                            var totalNumberOfCart = Cart.GetCartItemsCount(userLoggedIn);
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Cart" asp-action="Index"><i
                                    class="fas fa-shopping-cart"></i>&nbsp;Cart<span
                                    class="badge badge-pill badge-warning"
                                    id="totalCartCount">@totalNumberOfCart</span></a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user-circle"></i><strong> Welcome!</strong>,
                                    @User.Claims.FirstOrDefault(user => user.Type == ClaimTypes.Name).Value
                                    <i class="fas fa-chevron-down"></i>
                                </a>
                                <div class="dropdown-menu">

                                    <a class="dropdown-item" asp-controller="UserProfile" asp-action="Index"><i
                                        class="fas fa-user-circle"></i> View Profile</a>

                                    <a class="dropdown-item" asp-controller="Orders" asp-action="Index">&nbsp;<i
                                        class="fas fa-clipboard-list"></i>&nbsp;Orders</a>

                                    <hr />
                                    <a class="dropdown-item" asp-action="ProcessLogout" asp-controller="Account">&nbsp;<i
                                        class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
                                </div>
                            </li>

                        }
                        else
                        {
                            if (ViewData["Title"] != null && !ViewData["Title"].Equals("Login Page") &&
                            !ViewData["Title"].Equals("Register Account"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="Login" asp-controller="Account"><i
                                    class="fas fa-sign-in-alt"></i>&nbsp;Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link btn btn-gold" asp-controller="Register" asp-action="Index"><i
                                    class="fas fa-user-plus"></i> Register</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container-fluid" style="margin-top:100px;">
        <main role="main" class="pb-4">
            <div id="overlayLoadingDiv" style="display:none;" class="overlayDiv">
                <lottie-player src="https://assets7.lottiefiles.com/datafiles/ORpUnaV6z0mJ17E/data.json"
                    background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay>
                </lottie-player>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer" style="background-color:#e4e2da">
        <div class="jumbotron jumbotron-fluid ">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <picture>
                            <img src="~/images/icons/CandlePhotoFooter.png" class="img-fluid rounded shadow-lg"
                                alt="Responsive image">
                        </picture>
                    </div>
                    <div class="col-md-6 pt-2">
                        <h5>Let's get in touch!</h5>
                        <ul>
                            <li>
                                <img src="~/images/icons/Facebook-removebg-preview.png"
                                    class="imageFooter" /><strong>Facebook</strong>: <a
                                    href="#" onclick="openFacebook();">FlameandWaxPH13</a>
                            </li>
                            <li>
                                <img src="~/images/icons/Instagram-removebg-preview.png"
                                    class="imageFooter" /><strong>Instagram</strong>: <a
                                    href="#" onclick="openInstagram();">flameandwax13</a>
                            </li>
                            <li>
                                <img src="~/images/icons/Message-removebg-preview.png"
                                    class="imageFooter" /><strong>Phone Number</strong>: 0919-310-2347
                            </li>
                            <li>
                                <img src="~/images/icons/Gmail-removebg-preview.png"
                                    class="imageFooter" /><strong>Gmail</strong>: lianne.dalde.9@gmail.com
                            </li>
                            <li>
                                <img src="~/images/icons/Messenger-removebg-preview.png"
                                    class="imageFooter" /><strong>Messenger</strong>: flameandwax
                            </li>
                        </ul>
                    </div>
                </div>
                <hr />
                <p class="text-muted text-center">2021 | All Rights Reserved</p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/sweetalert/sweetalert.js"></script>
    <script src=@("https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js")></script>
    @RenderSection("Scripts", required: false)
</body>
</html>